#!/bin/bash
# WRITE STATUS TO JSON
CURDIR=$(dirname $0)
STATUS="$CURDIR/status"
TARGET="$CURDIR/server.json"
echo "STATUS-SCRIPT: $STATUS"
echo "TARGET-JSON: $TARGET"

if [ -f $TARGET ]
then
	rm $TARGET
else
	touch $TARGET
fi

$STATUS > $TARGET
exit 0
