#!/bin/bash
# SIMPLE WEBSERVER FOR HOSTS TO READ/MERGE/DISPLAY SERVER.JSON

# VARS & CONF
CURDIR=$(dirname $0)
CONF="$CURDIR/conf/server-host.conf"
source $CONF

CLIENTSSUM=${#CLIENTS[@]}
CLIENTSNUM=0
echo "> found $CLIENTSSUM clients"

for key in "${!CLIENTS[@]}";
do
	CLIENTNAME=$key
	CLIENTURL=${CLIENTS[$key]}
	CLIENTJSON="server.$CLIENTNAME.json"
	echo "> GRABBING CLIENT$CLIENTSNUM $CLIENTNAME"
	echo "	URL:	$CLIENTURL"
	echo "	JSON:	$CLIENTJSON"
	CLIENTJSONDIR="$CURDIR/data/$CLIENTJSON"
	DOWNLOAD=$(wget --quiet --no-check-certificate --show-progress --progress=bar:force $CLIENTURL)
	MOVE=$(mv ./index.html $CLIENTJSONDIR)
	CLIENTSNUM=$((CLIENTSNUM+1));
done


exit 0
