#!/bin/sh
# SIMPLE WEBSERVER FOR CLIENTS TO PROVIDE DATA.JSON
# $1 = PORT: DEFAULT: 7236
# $2 = NCCMD; DEFAULT: nc
# NCCMD = nc, netcat, netcat.traditional ...

if [ -z "$1" ]
then
	PORT=7236
	$2="nc"
else
	PORT=$1
fi

if [ -z "$2" ]
then
	NCCMD="nc"
else
	NCCMD="$2"
fi

PORT=7236
NCCMD="nc"				
CURDIR=$(dirname $0)
CONTENT="$CURDIR/server-index.bash"

(while true ; do nc -vl -p $PORT -c "$CONTENT"; done)
