#!/bin/sh
# SIMPLE WEBSERVER FOR CLIENTS TO PROVIDE SERVER.JSON
# $1 = PORT: DEFAULT: 7236
# $2 = NCCMD; DEFAULT: nc
# 

# VARS & CONF
CURDIR=$(dirname $0)
CONF="$CURDIR/conf/server-client.conf"

source $CLIENTCONF

if [ -z "$1" ]
then
	PORT=$PORT_default
	NCCMD="$NCCMD_default"
else
	PORT=$1
	echo "> using PORT $PORT"
fi

if [ -z "$2" ]
then
	NCCMD="$NCCMD_default"
else
	NCCMD="$2"
	echo "> using NCCMD $NCCMD"
fi
			
CURDIR=$(dirname $0)
CONTENT="$CURDIR/server-index.bash"

(while true ; do $NCCMD -l -p $PORT -c "$CONTENT" -vv; done)
