#!/bin/bash
# stateSRV - SIMPLE WEBSERVER FOR HOSTS TO READ/MERGE/DISPLAY SERVER.JSON

# VARS & CONF
CURDIR=$(dirname $0)
declare -A CLIENTS
CONF="$CURDIR/conf/server-host.conf"
. $CONF

CLIENTSSUM=${#CLIENTS[@]}
CLIENTSNUM=0
echo "> found $CLIENTSSUM clients"

for key in "${!CLIENTS[@]}";
do
	CLIENTNAME=$key
	CLIENTURL=${CLIENTS[$key]}
	CLIENTJSON="server.$CLIENTNAME.json"
	echo "> GRABBING CLIENT$CLIENTSNUM $CLIENTNAME"
	echo "	URL:	$CLIENTURL"
	echo "	JSON:	$CLIENTJSON"
	INDEXHTML="$CURDIR/index.html"
	CLIENTJSONDIR="$CURDIR/data/$CLIENTJSON"
	if [ -f /usr/local/bin/wget ]
	then
		WGET="/usr/local/bin/wget"
	else
		WGET=$(which wget)
	fi
	DOWNLOAD=$($WGET --quiet --no-check-certificate --show-progress --progress=bar:force -O $CLIENTJSONDIR $CLIENTURL)
	# MOVE=$(mv $INDEXHTML $CLIENTJSONDIR)
	CLIENTSNUM=$((CLIENTSNUM+1));
done


exit 0
